name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: gwatts/go-coverage-action@v2
      id: coverage
      with:
        cover-pkg: ./...
    
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: ${{ github.ref_name }}.html
