name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'
    - name: dependencies
      run: go get .
    - name: Test
      run: go test -cover -coverprofile=coverage.txt ./...
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: coverage.txt

  code_coverage:
    name: "Code coverage report"
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - uses: fgrosse/go-coverage-report@v1.0.1
